name: Build RustDesk Client (Final)

on:
  workflow_dispatch:
    inputs:
      config_json:
        description: 'Configuration JSON'
        required: true
        type: string
      executable_name:
        description: 'Executable name'
        required: true
        type: string
        default: 'rustdesk-custom'
      rustdesk_branch:
        description: 'RustDesk branch'
        required: false
        type: string
        default: 'master'
      target_arch:
        description: 'Target architecture'
        required: false
        type: choice
        options:
          - x86_64
          - aarch64
        default: 'x86_64'
      enable_portable:
        description: 'Enable portable mode'
        required: false
        type: boolean
        default: false
      include_installer:
        description: 'Include installer (alias for create_installer)'
        required: false
        type: boolean
        default: true
      create_installer:
        description: 'Create installer'
        required: false
        type: boolean
        default: true
      enable_debug:
        description: 'Enable debug mode'
        required: false
        type: boolean
        default: false

env:
  RUST_VERSION: 1.75
  LLVM_VERSION: 15.0
  VCPKG_COMMIT_ID: 6f29f12e82a8293156836ad81cc9bf5af41fe836

jobs:
  build-windows:
    name: Build RustDesk for Windows
    runs-on: windows-2022
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Checkout RustDesk
      uses: actions/checkout@v4
      with:
        repository: rustdesk/rustdesk
        ref: ${{ inputs.rustdesk_branch }}
        submodules: recursive
        path: rustdesk
        
    - name: Install LLVM and Clang
      uses: KyleMayes/install-llvm-action@v1
      with:
        version: ${{ env.LLVM_VERSION }}
        
    - name: Install Rust toolchain
      uses: dtolnay/rust-toolchain@v1
      with:
        toolchain: ${{ env.RUST_VERSION }}
        targets: x86_64-pc-windows-msvc
        components: "rustfmt"
        
    - uses: Swatinem/rust-cache@v2
      with:
        prefix-key: windows-2022
        workspaces: "rustdesk -> target"
        
    - name: Setup vcpkg with Github Actions binary cache
      uses: lukka/run-vcpkg@v11
      with:
        vcpkgDirectory: C:\vcpkg
        vcpkgGitCommitId: ${{ env.VCPKG_COMMIT_ID }}
        doNotCache: false
        
    - name: Install system dependencies
      shell: powershell
      run: |
        Write-Host "=== Installing system dependencies ==="
        choco install nsis -y --no-progress
        Write-Host "[SUCCESS] System dependencies installed"
        
    - name: Setup vcpkg environment
      shell: powershell
      run: |
        Write-Host "=== Setting up vcpkg environment ==="
        
        # Copy our vcpkg.json to rustdesk directory
        Write-Host "Copying vcpkg.json to rustdesk directory..."
        $source = "$env:GITHUB_WORKSPACE\vcpkg.json"
        $dest = "$env:GITHUB_WORKSPACE\rustdesk\vcpkg.json"
        
        if (-not (Test-Path $source)) {
          Write-Host "[ERROR] Source vcpkg.json not found: $source"
          exit 1
        }
        
        Copy-Item $source $dest -Force
        Write-Host "[SUCCESS] vcpkg.json copied successfully"
        
    - name: Install vcpkg dependencies
      shell: powershell
      run: |
        Write-Host "=== Installing vcpkg dependencies ==="
        cd "$env:GITHUB_WORKSPACE\rustdesk"
        
        Write-Host "Current directory: $(Get-Location)"
        Write-Host "vcpkg.json content:"
        Get-Content "vcpkg.json" | Write-Host
        
        Write-Host "Running vcpkg install..."
        & "$env:VCPKG_ROOT\vcpkg.exe" install --triplet x64-windows-static --x-install-root="$env:VCPKG_ROOT\installed"
        
        if ($LASTEXITCODE -ne 0) {
          Write-Host "[ERROR] vcpkg install failed with exit code: $LASTEXITCODE"
          Write-Host "=== Checking for error logs ==="
          Get-ChildItem "$env:VCPKG_ROOT" -Filter "*.log" -Recurse | ForEach-Object {
            Write-Host "=== $($_.FullName) ==="
            Get-Content $_.FullName | Write-Host
            Write-Host "========================"
          }
          exit 1
        }
        
        Write-Host "[SUCCESS] vcpkg dependencies installed successfully"
        
    - name: Apply configuration
      shell: powershell
      run: |
        Write-Host "=== Applying configuration ==="
        
        cd "$env:GITHUB_WORKSPACE\rustdesk"
        
        # Create config directory
        New-Item -Path "src\ui" -ItemType Directory -Force -ErrorAction SilentlyContinue | Out-Null
        
        # Write config JSON
        '${{ inputs.config_json }}' | Out-File -FilePath "src\ui\config.json" -Encoding UTF8
        
        # Parse configuration
        try {
          $config = '${{ inputs.config_json }}' | ConvertFrom-Json
        } catch {
          Write-Host "[ERROR] Failed to parse configuration JSON: $($_.Exception.Message)"
          exit 1
        }
        
        # Create simple Rust config file using separate lines
        $rustConfigLines = @()
        $rustConfigLines += "// Auto-generated configuration"
        $rustConfigLines += "pub const RENDEZVOUS_SERVER: &str = `"$($config.server.RENDEZVOUS_SERVER)`";"
        $rustConfigLines += "pub const RELAY_SERVER: &str = `"$($config.server.RELAY_SERVER)`";"
        $rustConfigLines += "pub const API_SERVER: &str = `"$($config.server.API_SERVER)`";"
        $rustConfigLines += "pub const KEY: &str = `"$($config.server.KEY)`";"
        $rustConfigLines += "pub const PRODUCT_NAME: &str = `"$($config.branding.PRODUCT_NAME)`";"
        $rustConfigLines += "pub const APP_NAME: &str = `"$($config.branding.APP_NAME)`";"
        
        $rustConfigLines | Out-File -FilePath "src\config.rs" -Encoding UTF8
        Write-Host "[SUCCESS] Rust config created"
        
        # Update Cargo.toml carefully - only update if different from rustdesk
        if (Test-Path "Cargo.toml") {
          $cargoContent = Get-Content "Cargo.toml" -Raw
          
          if ($config.branding.APP_NAME -ne "rustdesk") {
            $cargoContent = $cargoContent -replace 'name = "rustdesk"', "name = `"$($config.branding.APP_NAME)`""
            Write-Host "[SUCCESS] Updated package name in Cargo.toml"
          }
          
          $cargoContent | Out-File -FilePath "Cargo.toml" -Encoding UTF8
        }
        
        Write-Host "[SUCCESS] Configuration applied successfully"
        
    - name: Build RustDesk
      shell: powershell
      run: |
        Write-Host "=== Building RustDesk ==="
        
        cd "$env:GITHUB_WORKSPACE\rustdesk"
        
        # Set environment variables for build
        $env:VCPKG_ROOT = "C:\vcpkg"
        $env:VCPKG_DEFAULT_TRIPLET = "x64-windows-static"
        $env:LIBCLANG_PATH = "$env:PROGRAMFILES\LLVM\bin"
        $env:RUSTFLAGS = "-C target-feature=+crt-static"
        $env:RUST_BACKTRACE = "1"
        
        Write-Host "Starting Cargo build..."
        if ("${{ inputs.enable_debug }}" -eq "true") {
          Write-Host "Build mode: Debug"
        } else {
          Write-Host "Build mode: Release"
        }
        
        if ("${{ inputs.enable_debug }}" -eq "true") {
          Write-Host "[DEBUG] Building in debug mode..."
          cargo build --features inline --verbose
        } else {
          Write-Host "[RELEASE] Building in release mode..."
          cargo build --release --features inline --verbose
        }
        
        if ($LASTEXITCODE -ne 0) {
          Write-Host "[ERROR] Build failed with exit code $LASTEXITCODE"
          exit $LASTEXITCODE
        }
        
        Write-Host "[SUCCESS] Build completed successfully!"
        
    - name: Prepare artifacts
      shell: powershell
      run: |
        Write-Host "=== Preparing artifacts ==="
        
        cd "$env:GITHUB_WORKSPACE\rustdesk"
        
        try {
          $config = '${{ inputs.config_json }}' | ConvertFrom-Json
        } catch {
          Write-Host "[ERROR] Failed to parse config JSON"
          exit 1
        }
        
        $executableName = "${{ inputs.executable_name }}"
        $buildDir = if ("${{ inputs.enable_debug }}" -eq "true") { "target\debug" } else { "target\release" }
        
        Write-Host "Looking for executable in: $buildDir"
        
        # Find the built executable
        $possibleExes = @(
          "$buildDir\rustdesk.exe",
          "$buildDir\RustDesk.exe",
          "$buildDir\$($config.branding.APP_NAME).exe"
        )
        
        $builtExecutable = ""
        foreach ($exe in $possibleExes) {
          if (Test-Path $exe) {
            $builtExecutable = $exe
            Write-Host "[SUCCESS] Found executable: $exe"
            break
          }
        }
        
        if (-not $builtExecutable) {
          Write-Host "[ERROR] No executable found. Available files in $buildDir:"
          Get-ChildItem $buildDir -Filter "*.exe" -ErrorAction SilentlyContinue | ForEach-Object { Write-Host "  $($_.Name)" }
          exit 1
        }
        
        # Copy with custom name
        $finalExe = "$buildDir\$executableName.exe"
        if ($builtExecutable -ne $finalExe) {
          Copy-Item $builtExecutable $finalExe -Force
          Write-Host "[SUCCESS] Copied executable to: $finalExe"
        }
        
        # Create installer if requested (use include_installer if provided, otherwise fallback to create_installer)
        $shouldCreateInstaller = if ("${{ inputs.include_installer }}" -ne "") { "${{ inputs.include_installer }}" } else { "${{ inputs.create_installer }}" }
        if ($shouldCreateInstaller -eq "true") {
          Write-Host "Creating installer..."
          
          # Create installer script file
          $installerContent = @(
            "!define PRODUCT_NAME `"$($config.branding.PRODUCT_NAME)`"",
            "!define PRODUCT_VERSION `"1.0.0`"",
            "!define PRODUCT_PUBLISHER `"$($config.branding.PRODUCT_NAME)`"",
            "",
            "SetCompressor lzma",
            "RequestExecutionLevel admin",
            "",
            "Name `"`${PRODUCT_NAME}`"",
            "OutFile `"$executableName-installer.exe`"",
            "InstallDir `"`$PROGRAMFILES\`${PRODUCT_NAME}`"",
            "",
            "Section `"MainSection`" SEC01",
            "  SetOutPath `"`$INSTDIR`"",
            "  File `"$buildDir\$executableName.exe`"",
            "  CreateDirectory `"`$SMPROGRAMS\`${PRODUCT_NAME}`"",
            "  CreateShortCut `"`$SMPROGRAMS\`${PRODUCT_NAME}\`${PRODUCT_NAME}.lnk`" `"`$INSTDIR\$executableName.exe`"",
            "  CreateShortCut `"`$DESKTOP\`${PRODUCT_NAME}.lnk`" `"`$INSTDIR\$executableName.exe`"",
            "  WriteUninstaller `"`$INSTDIR\Uninstall.exe`"",
            "SectionEnd"
          )
          
          $installerContent | Out-File -FilePath "installer.nsi" -Encoding UTF8
          
          # Compile installer
          & "C:\Program Files (x86)\NSIS\makensis.exe" "installer.nsi"
          
          if ($LASTEXITCODE -eq 0) {
            Write-Host "[SUCCESS] Installer created successfully"
          } else {
            Write-Host "⚠️ Installer creation failed, but continuing..."
          }
        }
        
        Write-Host "[SUCCESS] Artifacts prepared successfully"
        
    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: rustdesk-client-${{ inputs.executable_name }}
        path: |
          rustdesk/target/debug/*.exe
          rustdesk/target/release/*.exe
          rustdesk/*.exe
        retention-days: 7