name: Test API Workflow

on:
  workflow_dispatch:
    inputs:
      test_param:
        description: 'Test parameter'
        required: false
        type: string
        default: 'hello'

jobs:
  test:
    name: Simple Test Job
    runs-on: ubuntu-latest
    
    steps:
    - name: Echo test
      run: |
        echo "Test parameter: ${{ inputs.test_param }}"
        echo "Workflow executed successfully via API!"