name: Test Manual Workflow

on:
  workflow_dispatch:
    inputs:
      test_input:
        description: 'Test input for manual trigger'
        required: false
        type: string
        default: 'Hello World'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Test manual execution
        run: |
          echo "Manual workflow triggered successfully!"
          echo "Test input: ${{ inputs.test_input }}"
          echo "Timestamp: $(date)"